logging: 
  level: 
    root: INFO

#spring:
#  thymeleaf:
#    cache: false
#    check-template: true
#    check-template-location: true
#    servlet:#      content-type: text/html 
#    enabled: true
#    encoding: UTF-8
#    # excluded-view-names:
#    # mode: HTML5
#    # prefix: /templates/
#    # suffix: .html
#    # template-resolver-order:
#    # view-names:
